---
- hosts: kafka 
  vars:
    jmx_exporter_version: 0.11.0
    jmx_exporter_service: kafka
    zookeeper_hosts:
     - host: node1
       id: 1
     - host: node2
       id: 2
     - host: node3
       id: 3
    kafka_zookeeper_hosts:
      - node1:2181,node2:2181,node3:2181
    kafka_hosts:
     - host: node1 # the machine running
       id: 1
     - host: node2  # the machine running
       id: 2
     - host: node3 # the machine running
       id: 3
  roles:
    - { role: java, become: yes }
    - { role: zookeeper, become: yes }
    - { role: kafka, become: yes }

